# Generated by Django 3.2.16 on 2023-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Название магазина')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание магазина')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
