# Generated by Django 3.2.16 on 2023-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoryproductmodel_productmodel_productpricemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='buy',
            field=models.BooleanField(default=False, help_text='Куплен ли продукт или нет', verbose_name='Куплен'),
        ),
    ]
